### ISSUE TITLE
[SUGGESTION] Mover função de formatar gráfico

### ISSUE THREAD

**Issue by DamasoMagno** [Jonatan966/my-cash#23]
O arquivo para formatar os gráficos da aplicação está localizado no diretório services. Porém, a pasta services deve ser apenas usada para a integração de serviços externos à aplicação. Recomendo mover esta funcionalidade para o diretório útils, visto que, esta pasta é usada para conter funcionalidades utilitárias da aplicação.

**Comment by Jonatan966** [comment]
Realmente. . . O único propósito dessa função é criar uma porcentagem, para ser usada no gráfico do `chart.js`, e isso não requer conexão com nenhum serviço externo.
Seria interessante também mudar o nome da função, pra ser mais descritivo. Qual nome você acha melhor?

**Comment by DamasoMagno** [comment]
Um nome recomendável para ela seria **formatChartPercentage**, pois ela tem a responsabilidade de calcular a porcentagem do valor da entrada sob o gráfico.

**Comment by Jonatan966** [comment]
Ótima sugestão, é um nome muito adequado!
Pode fazer a implementação, Só peço que aguarde até eu fechar essa PR #22
